In [0]:
import pandas as pd

In [0]:
df = pd.read_csv('desafio1.csv')

In [7]:
df.dtypes

RowNumber                     int64
id                           object
sobrenome                    object
pontuacao_credito             int64
estado_residencia            object
genero                       object
idade                         int64
nivel_estabilidade            int64
saldo_conta                 float64
numero_produtos               int64
possui_cartao_de_credito      int64
membro_ativo                  int64
dtype: object

In [8]:
# Gera um array com todos os estados do dataframe
estados = df['estado_residencia'].unique()
estados

array(['SC', 'RS', 'PR'], dtype=object)

In [0]:
# Calcula a média da pontuação de crédito para cada estado
res_mean = [df[df['estado_residencia'] == estado]['pontuacao_credito'].mean() for estado in estados]

In [0]:
# Calcula o desvio padrão da pontuação de crédito para cada estado
res_std = [df[df['estado_residencia'] == estado]['pontuacao_credito'].std() for estado in estados]

In [0]:
# Calcula a mediana da pontuação de crédito para cada estado
res_median =[df[df['estado_residencia'] == estado]['pontuacao_credito'].median() for estado in estados]

In [0]:
# Calcula a moda da pontuação de crédito para cada estado
# A moda e transformada em DataFrame para filtrar as colunas de dtype e index retornada pelo metodo mode()
res_mode = [df[df['estado_residencia'] == estado]['pontuacao_credito'].mode() for estado in estados]
res_mode = pd.DataFrame(res_mode)

In [0]:
#Cria um novo DataFrame formatado para exportar em formato JSON a moda, mediana, média e desvio padrão
df_formated = pd.DataFrame({'moda': res_mode[0],'mediana': res_median, 'media': res_mean, 'desvio_padrao': res_std}).set_index(estados)
res_final = df_formated.T.to_json(force_ascii=False)

In [0]:
#Abrindo e salvando arquivo submission.json

json = open('submission.json','w')
json.write(res_final)
json.close()